# -*- coding: utf-8 -*-
a = 1
def some_method
    p a
end

# 変数スコープが違うので NameError 例外になると本には書いてあるが、
# 実行してみると例外が投げられない??
